In [13]:
# part 1: Theoretical Part:
import numpy as np

A = np.array([[2,4,1,3],
              [5,0,-2,3],
              [0,-1,-3,4],
              [1,1,2,5]])
b = np.array([1,2,3,4])

print("A-inverse:", np.linalg.inv(A))

# x_theoretical = np.linalg.inv(A.T @ A) @ (A.T @ b)


A:
[[ 2  4  1  3]
 [ 5  0 -2  3]
 [ 0 -1 -3  4]
 [ 1  1  2  2]]
b: [1 2 3 4]
--------------------------------------------------------------
Theoretical Solution for X:
 [ 0.05405405 -1.08108108  1.16216216  1.35135135]


In [14]:
# part 2: Gradient Descent:
import numpy as np

# Example A and b (replace with your own)
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
b = np.array([1, 0, 1])

# Gradient descent parameters
alpha = 0.001     # learning rate
iterations = 1000

# Initialize x (zeros)
x = np.zeros(A.shape[1])

for i in range(iterations):
    # Compute gradient: ∇f(x) = 2 A^T (A x - b)
    grad = 2 * A.T.dot(A.dot(x) - b)

    # Update rule x = x - α ∇f(x)
    x = x - alpha * grad

# Final result
print("Estimated x:", x)

# Compare with theoretical least-squares solution
x_theoretical = np.linalg.inv(A.T @ A) @ (A.T @ b)
print("Theoretical x:", x_theoretical)

The value of X after 100 iterations is:
 [ 0.02011036 -0.34084217  0.4050907   0.92041009]
The value of X after 200 iterations is:
 [ 0.01272439 -0.64357435  0.71966108  1.11566054]
The value of X after 300 iterations is:
 [ 0.02741522 -0.82507846  0.90381785  1.21563631]
The value of X after 400 iterations is:
 [ 0.03821147 -0.93158398  1.01136537  1.27235452]
The value of X after 500 iterations is:
 [ 0.04477274 -0.99381473  1.07414506  1.30526827]
The value of X after 600 iterations is:
 [ 0.04863277 -1.03014495  1.11078875  1.32445682]
The value of X after 700 iterations is:
 [ 0.05088932 -1.05135086  1.13217682  1.33565405]
The value of X after 800 iterations is:
 [ 0.05220683 -1.06372831  1.1446605   1.34218929]
The value of X after 900 iterations is:
 [ 0.05297587 -1.07095272  1.15194689  1.3460037 ]
The value of X after 1000 iterations is:
 [ 0.05342474 -1.07516942  1.15619978  1.34823006]
--------------------------------------------------------------
Estimated X using the Grad